SET SQL_SAFE_UPDATES = 0;

DROP DATABASE IF EXISTS exemplos;
CREATE DATABASE exemplos;

USE exemplos;
CREATE TABLE ENDERECO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	RUA VARCHAR(255) NOT NULL,
	CEP VARCHAR(255) NOT NULL,
	ESTADO VARCHAR(255) NOT NULL,
	CIDADE VARCHAR(255) NOT NULL,
	NUMERO VARCHAR(255) NOT NULL,
	BAIRRO VARCHAR(255) NOT NULL
);

CREATE TABLE CLIENTE(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	SOBRENOME VARCHAR(255) NOT NULL,
	CPF VARCHAR(255) NOT NULL,
	IDENDERECO INT,
	FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO (IDENDERECO)
);

CREATE TABLE TELEFONE(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CODIGOPAIS VARCHAR(255) NOT NULL,
	DDD VARCHAR(255) NOT NULL,
	NUMERO VARCHAR(255) NOT NULL,
	TIPOLINHA VARCHAR(255) NOT NULL,
	ATIVO TINYINT NOT NULL,
	IDCLIENTE INT,
	FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);